### ISSUE TITLE
RgbLights Not working

### ISSUE THREAD

**Issue by gvsro** [ni-c/heimcontrol.js#114]
After almost 2 days of struggling to install heimctrl I finally made it work. Well most of it. The RgbLights won`t work. 

What works:
I set the pwm pins to Arduino LED and set them on or off.
The fade example app from duino folder.
I set the pwm value over serial. (ex: '!0311150.').
I know allmost nothing about node or socket.io.. how to debug it or how to sniff traffic but what I know is the serial. I made a loop from the ttyUSB0 to ttyAMA0 so I would know if the packets from the rgb module pass. Well they don`t.
How can I set heim in debug?

**Comment by ConnorRoberts** [comment]
Have you tested the Arduino plugin with just an LED or something simple, does that work?

Things to try:
> The fade example app from duino folder.

I didn't understand what you meant here, what have you uploaded to the Arduino? It should be the code at: 
https://github.com/ni-c/duino/blob/master/src/duino/duino.ino

If that's right, then if you open up "plugins/rgblights/index.js" and change line 23 from
```
this.board = new duino.Board();
```

to 
```
this.board = new duino.Board({debug: true});
```

that would enable debugging for the communication between the heimcontrol and the arduino, it should then output details of when commands are sent to the arduino. Is it sending the commands?

**Comment by ConnorRoberts** [comment]
Have replied to your email as well :)
