### ISSUE TITLE
starting error (node heimcontrol.js)

### ISSUE THREAD

**Issue by ttherbrink** [ni-c/heimcontrol.js#117]
after a fresh install of heimcontrol i cant get it to work anymore.

> root@raspberrypi:/heimcontrol.js# sudo node heimcontrol.js
> Failed to load c++ bson extension, using pure JS version
> WARNING: Change secret string in config/development.json
>    info  - socket.io started
> connect.multipart() will be removed in connect 3.0
> visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
> connect.limit() will be removed in connect 3.0
> heimcontrol.js listening on port 8080
> /heimcontrol.js/node_modules/requirejs/bin/r.js:378
>         throw err;
>               ^
> Error: Tried loading "piswitch" at /heimcontrol.js/piswitch.js then tried node's require("piswitch") and it failed with error: Error: Cannot find module '../build/Release/wiringPi'
>     at /heimcontrol.js/node_modules/requirejs/bin/r.js:2512:27
>     at Object.context.execCb (/heimcontrol.js/node_modules/requirejs/bin/r.js:1876:33)
>     at Object.Module.check (/heimcontrol.js/node_modules/requirejs/bin/r.js:1110:51)
>     at Object.Module.enable (/heimcontrol.js/node_modules/requirejs/bin/r.js:1381:22)
>     at Object.Module.init (/heimcontrol.js/node_modules/requirejs/bin/r.js:1018:26)
>     at callGetModule (/heimcontrol.js/node_modules/requirejs/bin/r.js:1408:63)
>     at Object.context.completeLoad (/heimcontrol.js/node_modules/requirejs/bin/r.js:1770:21)
>     at Function.req.load (/heimcontrol.js/node_modules/requirejs/bin/r.js:2525:17)
>     at Object.context.load (/heimcontrol.js/node_modules/requirejs/bin/r.js:1865:21)
>     at Object.Module.load (/heimcontrol.js/node_modules/requirejs/bin/r.js:1064:29)

**Comment by tjanson** [comment]
Hi, sorry about that – PiSwitch is my plugin and it (or its dependency `wiringPi`) seem to cause trouble these days. (I’m not using Heimcontrol myself at the moment.)

The workaround is to [remove the plugin folder and its entry in `package.json` as I previously described here](https://github.com/ni-c/heimcontrol.js/issues/104#issuecomment-70097592). If you still have trouble, let me know.
