### ISSUE TITLE
Issues with ni-c du.ino code

### ISSUE THREAD

**Issue by pete54321** [ni-c/heimcontrol.js#119]
Hi all, 

Very new to this so bear with me. I'm trying to get RC communication to work with heimcontrol. 

When setting heimcontrol up I found that it didn't work with the arduino script from this repository uploaded, so I used the one over at https://github.com/ecto/duino 
However, this doesn't work with RC communication.

When I upload the script from this repository, the arduino is seemingly unresponsive when plugged into the Pi. There is no sign of communication and it won't even turn on an LED.
Is there something I'm missing when I upload the code from https://github.com/ni-c/duino/tree/master/src/duino ? Is there anything extra I need to do on the Pi? 

Thanks in advance.

**Comment by dejersey** [comment]
Greetings, from the future. 
Make sure you use the libraries in the duino repository.
