### ISSUE TITLE
can i use only arduino alone ?

### ISSUE THREAD

**Issue by moeinrahimi** [ni-c/heimcontrol.js#138]
hi

can i use only arduino alone ? (without raspberry pi)

**Comment by tjanson** [comment]
Depends on what you’re trying to do. The Raspberry Pi acts as the webserver for Heimcontrol. You can use a different (Linux-based) computer for that, it doesn’t have to be a Pi.

If you’re just interested in interfacing you PC with an Arduino, have a look at [ni-c/duino](https://github.com/ni-c/duino) — which Heimcontrol uses, but is in principle unrelated.

Note that both projects are currently unmaintained (have a look at the most recent commits — at least a year ago), and may or may not work without tweaking.

**Comment by moeinrahimi** [comment]
@tjanson 
thanks for quick reply, is there a better alternative form home automation ? at least one with active development

**Comment by tjanson** [comment]
No, I haven't followed home automation in a while, so I don't have any
recommendations.
