### ISSUE TITLE
how to close properly heimcontrol.js server?

### ISSUE THREAD

**Issue by dammianhr** [ni-c/heimcontrol.js#52]
hello,
i follow all the steps to install and the first time run nice! close the ssh windows and re run heimcontrol.js

/home/pi/heimcontrol.js/node_modules/mongodb/lib/mongodb/db.js:286
          throw err;
                ^
ReferenceError: requirejs is not defined
    at requireRecursive (/home/pi/heimcontrol.js/libs/PluginHelper.js:57:7)
    at PluginHelper.getPluginList (/home/pi/heimcontrol.js/libs/PluginHelper.js:67:5)
    at /home/pi/heimcontrol.js/heimcontrol.js:167:32
    at /home/pi/heimcontrol.js/node_modules/mongodb/lib/mongodb/db.js:283:11
    at process._tickCallback (node.js:415:13)

anyone know what happens?

if remove, reinstall heimcontrol.js... run nice.

**Comment by viru-git** [comment]
How to run heimcontrol.js on windows system, what installations are required and what is the procedure to follow.
